<?php

/** @var \Phalcon\Mvc\View\Engine\Php $this */
/** @var \Phalcon\Mvc\ModelInterface $items */
/** @var \AutoAdmin\Helpers\FieldsCollection $fields */
/** @var \Phalcon\Paginator\Adapter\Model $paginator */

$tottalPages = $paginator->total_pages;

$startNum = 1;
$pagesLimit = 10;

$startNum = $paginator->current;

$entityName = $this->dispatcher->getParam('entity');

?>
<div class="pagination">
    <ul>
        <li<?php echo 1 == $paginator->current ? ' class="disabled"' : '' ?>><a href="<?php echo $this->url->get([ 'for' => 'admin-entity' , 'entity' => $entityName ]) ?>">Первая</a></li>
        <li<?php echo $paginator->before == $paginator->current ? ' class="disabled"' : '' ?>>
            <a href="<?php echo $this->url->get([ 'for' => 'admin-entity' , 'entity' => $entityName ] , [ 'page' => $paginator->before ]) ?>">&larr; Предыдущая</a>
        </li>
        <?php for ( $pageNum = $startNum; $pageNum <= $pagesLimit; $pageNum++ ): ?>
            <li<?php echo $pageNum == $paginator->current ? ' class="active"' : '' ?>>
                <a href="<?php echo $this->url->get([ 'for' => 'admin-entity' , 'entity' => $entityName ] , [ 'page' => $pageNum ]) ?>"><?php echo $pageNum ?></a>
            </li>
        <?php endfor; ?>
        <li<?php echo $paginator->next == $paginator->current ? ' class="disabled"' : '' ?>>
            <a href="<?php echo $this->url->get([ 'for' => 'admin-entity' , 'entity' => $entityName ] , [ 'page' => $paginator->next ]) ?>">Следующая &rarr;</a>
        </li>
        <li<?php echo $paginator->last == $paginator->current ? ' class="disabled"' : '' ?>>
            <a href="<?php echo $this->url->get([ 'for' => 'admin-entity' , 'entity' => $entityName ] , [ 'page' => $paginator->last ]) ?>">Последняя (<?php echo $paginator->total_pages ?>)</a>
        </li>
    </ul>
</div>
