<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 * @var array $navItems
 * @var string $active
 *
 */

?>

<ul class="nav">
    <?php foreach ($navItems as $entity => $label): ?>
        <li<?php echo $entity==$active ? ' class="active"' : '' ?>><a href="<?php echo $this->url->get(['for' => 'admin-entity', 'entity' => $entity]) ?>"><?php echo $label; ?></a></li>
    <?php endforeach; ?>
</ul>

