<?php

/** @var \Phalcon\Mvc\View\Engine\Php $this */
/** @var \AutoAdmin\Fields\Field $field */
/** @var \Phalcon\Mvc\ModelInterface $model */
/** @var \AutoAdmin\Helpers\FieldParams $params */
/** @var array $tag */


if ($params->getParam('editor')) {

    /**
     * @todo переделать
     */
    $this->assets
        ->addJs('admin_assets/js/plugins/ckeditor/ckeditor.js')
        ->addJs('admin_assets/js/fields/editor/editor.js');

    $tag['class'] = 'editor form-control';
}

echo $this->tag->textArea($tag);
