<?php

/**
 * Шаблон страница авторизации в панели управления
 */

/** @var \Phalcon\Mvc\View\Engine\Php $this */

use AutoAdmin\Widgets\Widget;
use AutoAdmin\Helpers\AdminAuthHelper;

?>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <span class="brand-logo"></span>
            <a class="navbar-brand" href="/admin">
                <?php echo $this->config->site->name ?>
            </a>
        </div>
    </div>
</div>


<div class="container content">

    <div class="content">
        <?php echo $this->getContent() ?>
    </div>

</div>
