<?php

/**
 * Шаблон внутренних страниц панели управления
 */

/** @var \Phalcon\Mvc\View\Engine\Php $this */

use AutoAdmin\Widgets\Widget;
use AutoAdmin\Helpers\AdminAuthHelper;

?>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <span class="brand-logo"></span>
        <a class="navbar-brand" href="/admin">
            <?php echo $this->config->site->name ?>
        </a>
        </div>
        <div class="collapse navbar-collapse">
            <?php echo Widget::factory('Navbar')->render(); ?>
            <ul class="nav navbar-nav pull-right">
                <li><a href="/admin/logout"><?php echo AdminAuthHelper::instance()->getUser()->username ?>, выйти</a></li>
            </ul>
        </div>
    </div>
</div>

<div class="container content">

    <?php echo Widget::factory('Breadcrumbs' , true)->render(); ?>

    <?php $this->flashSession->output() ?>

    <div class="content">
        <?php echo $this->getContent() ?>
    </div>

</div>

<div class="navbar visible-lg" id="phadmin-footer"">
    <div class="container">
        <ul class="nav pull-right">
            <li>
                <a href="#">&#169; 2013 - <?php echo sprintf('%s - %s. phalcon: %s' , date('Y') , $this->config->site->name, \Phalcon\Version::get()); ?></a>
            </li>
        </ul>
    </div>
</div>
