<?php

/** @var \Phalcon\Mvc\View\Engine\Php $this */
/** @var \Phalcon\Mvc\ModelInterface $item */
/** @var \AutoAdmin\Helpers\FieldsCollection $fields */

use AutoAdmin\Fields\ExternalField;

$entity = $this->dispatcher->getParam('entity');
$action = $this->dispatcher->getActionName();

$form_action = $this->url->get(
    [
    'for'    => 'admin-action' ,
    'entity' => $entity ,
    'action' => 'save' ,
    'params' => $item->id
    ]
);
$back_url = $this->url->get(
    [
    'for'    => 'admin-entity' ,
    'entity' => $entity
    ]
);

?>
<div class="container">
    <form action="<?php echo $form_action ?>" method="POST" class="form-horizontal">

        <div class="page-header">
            <div class="pull-right">
                <a href="<?php echo $back_url ?>" class="btn"><i class="glyphicon glyphicon-backward"></i> Назад</a>
                <input type="submit" value="Cохранить" class="btn btn-success"/>
            </div>
            <h1><?php echo $this->entityManager->getProperty($entity , 'title') ?> / Редактировать</h1>
        </div>

        <?php
        foreach ( $fields->toArray() as $field ) :
            if ( $field instanceof ExternalField ) {
                continue;
            }

            echo $field->render($action);
        endforeach;
        ?>

        <div class="control-group btn-toolbar">
            <div class="btn-group">
                <input class="btn btn-success" type="submit" value="Применить"/>
                <input class="btn btn-success" type="submit" value="Сохранить"/>
            </div>
            <a class="btn" href="<?php echo $back_url ?>">Закрыть</a>
        </div>
        <div class="form-horizontal">
            <?php
            foreach ( $fields->toArray() as $field ) {
                if ( !$field instanceof ExternalField ) {
                    continue;
                }

                echo $field->render($action);
            }
            ?>
        </div>

    </form>
</div>
