<?php

/** @var \Phalcon\Mvc\View\Engine\Php $this */
/** @var array $entities */
/** @var \AutoAdmin\Models\AdminUsers[] $users */

?>
<div class="row">
    <div class="col-md-6">
        <div class="page-header" style="margin-top: 0;">
            <h2>Сущности</h2>
        </div>
        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>Сущность</th>
                <th class="col-md-1">Записей</th>
                <th class="col-md-1"></th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ( $entities as $entity => $params ) :
                $list_href = $this->url->get([ 'for' => 'admin-entity' , 'entity' => $entity ]);
                $new_href  = $this->url->get([ 'for' => 'admin-action' , 'entity' => $entity , 'action' => 'edit' ]);
                $items     = $entity::count();
                ?>
                <tr>
                    <td><a href="<?php echo $list_href ?>"><?php echo $params['title'] ?></a></td>
                    <td class="col-md-1"><?php echo number_format($items , 0 , '.' , ' ') ?></td>
                    <td class="col-md-1">
                        <a href="<?php echo $new_href ?>" class="btn btn-mini" title="Добавить запись">
                            <i class="glyphicon glyphicon-plus"></i>
                        </a>
                    </td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    </div>
    <div class="col-md-6">
        <div class="page-header" style="margin-top: 0;">
            <h2>Администраторы</h2>
        </div>
        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>Логин</th>
                <th class="col-md-4">Последний визит</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ( $users as $user ) : ?>
                <tr>
                    <td><?php echo $user->username ?></td>
                    <td><?php echo date(DATE_RFC850 , strtotime($user->last_login)) ?></td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>
