<?php

/** @var \Phalcon\Mvc\View\Engine\Php $this */

use AutoAdmin\Widgets\Widget;
use AutoAdmin\Helpers\AdminAuthHelper;

?>
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $this->config->site->name ?></title>
    <meta name="robots" content="noindex">

    <!-- <link rel="shortcut icon" type="image/x-icon" href="favicon.ico" /> -->
    <?php $this->assets->outputCss('autoadmin_css') ?>

</head>
<body>

<?php echo $this->getContent() ?>

<?php $this->assets->outputJs('autoadmin_js') ?>

</body>
</html>
