<?php

/** @var \Phalcon\Mvc\View\Engine\Php $this */
/** @var \Phalcon\Tag $this->tag */

$this->getDi()->get('assets')
    ->collection('autoadmin_css')
    ->addCss('css/login.css');

?>
<div class="container">
    <?php echo $this->flashSession->output(); ?>
    <form class="form-signin" action="<?php echo $this->url->get(array('for' => 'admin-login')) ?>" method="post">
        <h2 class="form-signin-heading">Авторизация</h2>
        <?php echo $this->tag->textField(['username', 'size' => '30', 'class' => 'form-control','placeholder1'=>'Логин','autofocus'=>true]); ?>
        <?php echo $this->tag->passwordField(['password', 'size' => '30', 'class' => 'form-control','placeholder1'=>'Пароль',]); ?>
        <?php echo $this->tag->submitButton(['Войти', 'class' => 'btn btn-lg btn-primary btn-block']) ?>
    </form>
</div>
